services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - "redisinsightdata:/data"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    # image: python:3.10-alpine
    volumes:
      - .:/app
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
    ports:
      - "8000:5000"

volumes:
  redisdata:
  redisinsightdata: