FROM python:3.10-alpine
WORKDIR /code
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
WORKDIR /app
CMD ["celery", "-A", "tasks", "worker", "--loglevel=INFO"]

